sudo: required
dist: xenial

os:
  - linux
  - osx

osx_image: xcode9.4

services:
  - docker

env:
  global:
    - secure: hRHTlAuSUqjjgUuCKDaCWYCPOdEYgnz4JOEuglaG6NnbLNx/UxWR9alxk41kdwLGH7cmN/Z7ZFWLffA0m49j3mKiNwY7fscHg7iyCTkwhfOK0F8PbYs23NqSW8dedkivwE/YC6QO8ElOO8RhqMmNZJO77v2XRmZfU4btfw40uyX3jkbyZjnj6a0SDzCWK8zCQxoaG3YPml1gsdn5QZ5hUMY79GAnVeufNJXjPNRwVZnSBD/2c95S64b6Slsx2XoTNXDUgzJFncCbmeYZGMgNbUWBG8968ew3Ck+TNG2oiH8Y8FZHgeKayJqNLC1QvRsgdiqBCci5Ve6+s8mVxikhdgYGJJXcn7G9vW2BV71U6YryRRyZPUUyj2vwAzZwSiiasQGLe0o1MEFuV/gN7M6p4m07XDYDXQogImVruvYbQXwk223/7IqnDkeHg1jzrxlx4nBgEddZKSlASG+l+2kw68XC6efB4Fm6kOId0MP00wG6PzhtywfGwIOML0QWof+XCCv8sUBz2aTLN1KXw/Bnsl5kRfAXwvDNYGMA3j1u5tCw9762qY9loenWLC/7+IZTnc4QHgCW3ZjSL0CQfMkOsGIP5fzKBeSt8/aXpXhNeEad3qkcSMeGDbs1a11zn2oKjjd0YyjoXj/GvefZe7a4tOWbBqF6ow9w6UjwCHwftM8=
    - secure: o4T5hXAk2mQHYLjZ+Yr/JwMkgfe5gvjm8XLVIJ4BNsO0OpW7oXQ5Hcw8nKYlF3HEGjHkdW+nHeKFtYivI32Yu6QYvUQK0Titp91LELPKgMpz8IvpksI3SbAyQOw6trDhoV/3r0kBT2Xjw2Q8aXjH9e55Ogw6G+MhiKCJL3/y8ECofjssPNaSAJO9AEbG658KMRYL9BTjMkLJlhkeaIwTvPMWBGdIpMIll6uD1xa0iMaB1taWT0oEapuY8rygF10YgKOrsRf/P5kfd742MxdJkbMhOQcgXb6SK7yjkGp6gMbv5rktpCK+7UfQQC8ibmoI/JMjeKDLoB6eVIbWMGBHcfcgWFqIFq4sT39kCl4ZbZZ+MU77mCVqq6UA6Vy/n8tbSICJvjkaBa//6pu+oAWYsTFFLN6beAxDB1RsS78m+ejMznPX2v2KI2bHmZp2qXRdN7csp6nCXJl1b3rWhrKuIdmhS5PFAvuCXMDxpOSPhNdEa8akonISy7SGQL4jgoINsLpRrKQFpLHzcan8UHQVVg4UuRugqZ2pYYoUaP2YMbjOKg1VgKZjALlFiNIKRqlDLNT24gakSJ9OFAU45TXE8gUEpA6JyfQuP6fwrD9TwhAdLSxjQkfNT0X3Nd/aAu4AxPNI7Ra0eoIW8/O+WvVT8jK0Qfg8bH0nMIYRgVPcbmc=

language: java

addons:
  apt:
    packages:
      - maven
      - python3
      - python3-setuptools
      - python3-pip
      - r-base
      - libxml2-dev
  homebrew:
    packages:
      - r
    update: true

install:
  - sudo pip3 install --upgrade pip
  - sudo pip3 install cmake
  - sudo -H pip3 install --upgrade setuptools wheel virtualenv
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/emulator
  # install required packages for R
  - sudo -H R --vanilla -e 'install.packages("knitr", repos="http://cran.us.r-project.org")'
  - sudo -H R --vanilla -e 'install.packages("reticulate", repos="http://cran.us.r-project.org")'

before_script:
  # need to build in manylinux docker container!
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull dockcross/manylinux-x64 ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -e TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR dockcross/manylinux-x64 /bin/bash -c "/opt/python/cp36-cp36m/bin/pip3.6 install cmake && cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed .. && make && make install" ;
    fi
  # build for mac
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/installed .. && make && make install ;
    fi
  - sudo -H pip3 install $TRAVIS_BUILD_DIR/python-package
  - cd $TRAVIS_BUILD_DIR/r-package/brainflow && sudo -H R CMD build . && sudo -H R CMD INSTALL brainflow_0.0.0.9000.tar.gz
  - cd $TRAVIS_BUILD_DIR/tests/cpp && mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/installed .. && make
  - cd $TRAVIS_BUILD_DIR && cd java-package/brainflow && mvn package

script:
  # tests for cyton
  - sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_get_data.py --log --board 0 --port 
  - sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py Rscript $TRAVIS_BUILD_DIR/tests/r/brainflow_get_data.R
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/installed/lib python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py $TRAVIS_BUILD_DIR/tests/cpp/build/test_get_data 0
  # temp disable java test
  # - cd $TRAVIS_BUILD_DIR/tests/java/ && sudo -H javac -classpath $TRAVIS_BUILD_DIR/java-package/brainflow/target/brainflow-java-jar-with-dependencies.jar BrainFlowTest.java && ls -l . && sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py java -classpath ".:$TRAVIS_BUILD_DIR/java-package/brainflow/target/brainflow-java-jar-with-dependencies.jar" BrainFlowTest 0
  # tests for synthetic board
  - python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_get_data.py --log --board -1 --port "smth"
  - python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_multiboard_get_data.py --log --first-board -1 --first-port "smth1" --second-board -1 --second-port "smth2"
  - $TRAVIS_BUILD_DIR/tests/cpp/build/test_get_data -1 "smth"
  # tests for cyton daisy
  - sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_get_data.py --log --board 2 --port 
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/installed/lib python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/cyton_linux.py $TRAVIS_BUILD_DIR/tests/cpp/build/test_get_data 2
  # tests for novaxr
  - sudo -H python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/novaxr_udp.py python3 $TRAVIS_BUILD_DIR/tests/python/brainflow_get_data.py --board 3 --port 127.0.0.1
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/installed/lib python3 $TRAVIS_BUILD_DIR/emulator/brainflow_emulator/novaxr_udp.py $TRAVIS_BUILD_DIR/tests/cpp/build/test_get_data 3 127.0.0.1

after_success:
  - sudo -H pip3 install awscli
  - aws s3 cp $TRAVIS_BUILD_DIR/installed/lib/ s3://brainflow-artifacts/$TRAVIS_COMMIT/$TRAVIS_OS_NAME --recursive
  # notify that everything is ok
  - echo success > ${TRAVIS_OS_NAME}_success && aws s3 cp ${TRAVIS_OS_NAME}_success s3://brainflow-artifacts/$TRAVIS_COMMIT/

notifications:
  email:
    on_success: never
    on_failure: always
